# Generated by Django 6.0.6 on 2026-06-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
