# Generated by Django 6.0.6 on 2026-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
