# Generated by Django 6.0.6 on 2026-06-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='zipcode',
        ),
    ]
