# Generated by Django 6.0.6 on 2026-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default='Worcester', max_length=100)),
                ('state', models.CharField(default='MA', max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
