# Generated by Django 6.0.6 on 2026-06-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersettings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='neighborhood',
        ),
    ]
