# Generated by Django 6.0.6 on 2026-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_usersetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='Coordinates',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='street_address',
            field=models.CharField(default='1 Officer Manny Familia Wy', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='zip_code',
            field=models.CharField(blank=True, default='01605', max_length=10, null=True),
        ),
    ]
