# Generated by Django 6.0.6 on 2026-06-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usersetting_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='Coordinates',
            new_name='coordinates',
        ),
    ]
