# Generated by Django 6.0.6 on 2026-06-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_coordinates_usersetting_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='coordinates',
            new_name='coordinatesx',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='coordinatesy',
            field=models.CharField(blank=True, null=True),
        ),
    ]
